version: "3.9"

services:
    app:
        build: .
        container_name: laravel-app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - LOG_CHANNEL=stack
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
            - SESSION_DRIVER=file
            - SESSION_LIFETIME=120
        command: >
            sh -c "
              mkdir -p database &&
              touch database/database.sqlite &&
              chmod -R 777 database storage bootstrap/cache &&
              php-fpm -D &&
              nginx -g 'daemon off;'
            "
