version: "3.9"

services:
    app:
        build: .
        container_name: laravel-app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - LOG_CHANNEL=stack
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
