services:
    app:
        build: .
        container_name: nex-procure
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - LOG_CHANNEL=stack
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
        command: >
            sh -c "
              mkdir -p database &&
              touch database/database.sqlite &&
              chmod 777 database/database.sqlite &&
              php artisan migrate --force &&
              php-fpm -D &&
              nginx -g 'daemon off;'
            "
